
import { useState } from "react";
import {
    Bot,
    Lightbulb,
    Brain,
    Save,
} from "lucide-react";

const STORAGE_KEY = "aipms_developer_ai_preferences";

const DEFAULT_SETTINGS = {
    aiRecommendations: true,
    taskSuggestions: true,
    productivityInsights: true,
    aiNotifications: true,
    suggestionFrequency: "balanced",
    taskUnderstanding: true,
    taskRecommendations: true,
    codeSuggestions: false,
    progressInsights: true,
    workPlanning: true,
};

function loadSettings() {
    try {
        const saved = localStorage.getItem(STORAGE_KEY);

        if (!saved) {
            return DEFAULT_SETTINGS;
        }

        return {
            ...DEFAULT_SETTINGS,
            ...JSON.parse(saved),
        };
    } catch {
        return DEFAULT_SETTINGS;
    }
}

export default function AIPreferences() {
    const [settings, setSettings] = useState(loadSettings);
    const [message, setMessage] = useState("");

    const toggle = (key) => {
        setSettings((previous) => ({
            ...previous,
            [key]: !previous[key],
        }));

        setMessage("");
    };

    const handleSave = () => {
        try {
            localStorage.setItem(
                STORAGE_KEY,
                JSON.stringify(settings)
            );

            setMessage(
                "AI preferences updated successfully."
            );
        } catch {
            setMessage(
                "Unable to update AI preferences. Please try again."
            );
        }
    };

    const options = [
        {
            key: "aiRecommendations",
            title: "AI Recommendations",
            description: "Allow AI to provide recommendations.",
        },
        {
            key: "taskSuggestions",
            title: "AI Task Suggestions",
            description: "Receive AI-powered task suggestions.",
        },
        {
            key: "productivityInsights",
            title: "Productivity Insights",
            description: "Allow AI to analyze productivity information.",
        },
        {
            key: "aiNotifications",
            title: "AI Notifications",
            description: "Receive notifications generated by AI features.",
        },
        {
            key: "taskUnderstanding",
            title: "Task Understanding",
            description: "Use AI to help understand task requirements.",
        },
        {
            key: "taskRecommendations",
            title: "Task Recommendations",
            description: "Allow AI to recommend actions for assigned tasks.",
        },
        {
            key: "codeSuggestions",
            title: "Code-Related Suggestions",
            description: "Enable code-related AI assistance when integrated.",
        },
        {
            key: "progressInsights",
            title: "Progress Insights",
            description: "Receive AI insights about development progress.",
        },
        {
            key: "workPlanning",
            title: "Work Planning",
            description: "Allow AI to provide work planning suggestions.",
        },
    ];

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-3">
                <div className="rounded-xl bg-purple-100 p-3 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400">
                    <Bot size={22} />
                </div>

                <div>
                    <h2 className="text-xl font-semibold text-slate-900 dark:text-white">
                        AI Preferences
                    </h2>

                    <p className="text-sm text-slate-500 dark:text-slate-400">
                        Customize how AI assistance is provided.
                    </p>
                </div>
            </div>

            {message && (
                <div className="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700 dark:border-green-800 dark:bg-green-900/20 dark:text-green-400">
                    {message}
                </div>
            )}

            <div className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800">
                <div className="mb-5 flex items-center gap-3">
                    <Lightbulb
                        size={20}
                        className="text-yellow-500"
                    />

                    <h3 className="font-semibold text-slate-900 dark:text-white">
                        AI Suggestion Frequency
                    </h3>
                </div>

                <select
                    value={settings.suggestionFrequency}
                    onChange={(event) =>
                        setSettings((previous) => ({
                            ...previous,
                            suggestionFrequency: event.target.value,
                        }))
                    }
                    className="w-full rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500 dark:border-slate-600 dark:bg-slate-700 dark:text-white"
                >
                    <option value="low">Low</option>
                    <option value="balanced">Balanced</option>
                    <option value="high">High</option>
                </select>
            </div>

            <div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800">
                {options.map((option) => (
                    <div
                        key={option.key}
                        className="flex items-center justify-between border-b border-slate-200 p-5 last:border-b-0 dark:border-slate-700"
                    >
                        <div className="flex items-start gap-4">
                            <Brain
                                size={20}
                                className="mt-1 text-purple-500"
                            />

                            <div>
                                <h3 className="font-medium text-slate-900 dark:text-white">
                                    {option.title}
                                </h3>

                                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                                    {option.description}
                                </p>
                            </div>
                        </div>

                        <button
                            type="button"
                            onClick={() => toggle(option.key)}
                            className={`relative h-6 w-11 rounded-full transition ${
                                settings[option.key]
                                    ? "bg-purple-600"
                                    : "bg-slate-300 dark:bg-slate-600"
                            }`}
                            aria-label={`Toggle ${option.title}`}
                        >
                            <span
                                className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${
                                    settings[option.key]
                                        ? "left-6"
                                        : "left-1"
                                }`}
                            />
                        </button>
                    </div>
                ))}
            </div>

            <div className="flex justify-end">
                <button
                    type="button"
                    onClick={handleSave}
                    className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-2 text-sm font-medium text-white hover:bg-blue-700"
                >
                    <Save size={17} />
                    Save AI Preferences
                </button>
            </div>
        </div>
    );
}
