import { useEffect, useState } from "react";

import {
    Bell,
    CheckCircle2,
    Mail,
    Monitor,
    FolderKanban,
    Users,
    ShieldAlert,
    BrainCircuit,
    Wrench,
    RotateCcw,
    Save,
    X,
    AlertCircle,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";

// ============================================================
// SETTING-001
// MANAGE NOTIFICATION PREFERENCES
//
// Allows the authenticated admin to configure:
//
// - Email notifications
// - In-app notifications
// - Project notifications
// - User management notifications
// - Security alerts
// - AI-generated alerts
// - System maintenance notifications
//
// Current implementation:
// Frontend/localStorage
//
// Future implementation:
// Replace localStorage functions with API/database calls.
// ============================================================


// ============================================================
// CONFIGURATION
// ============================================================
//
// Notification types are represented as configurable system
// data instead of putting the settings directly into the UI.
//
// Later these can come from your backend/database.
// ============================================================

const DEFAULT_NOTIFICATION_TYPES = [
    {
        id: "emailNotifications",
        name: "Email Notifications",
        description:
            "Receive important AI-PMS notifications through email.",
        icon: Mail,
    },

    {
        id: "inAppNotifications",
        name: "In-App Notifications",
        description:
            "Receive notifications inside the AI-PMS application.",
        icon: Monitor,
    },

    {
        id: "projectNotifications",
        name: "Project Notifications",
        description:
            "Receive notifications about project updates, changes, and activities.",
        icon: FolderKanban,
    },

    {
        id: "userManagementNotifications",
        name: "User Management Notifications",
        description:
            "Receive notifications about user creation, updates, roles, and account changes.",
        icon: Users,
    },

    {
        id: "securityAlerts",
        name: "Security Alerts",
        description:
            "Receive alerts about important security and account activities.",
        icon: ShieldAlert,

        // Mandatory security notifications cannot be disabled.
        mandatory: true,
    },

    {
        id: "aiGeneratedAlerts",
        name: "AI-Generated Alerts",
        description:
            "Receive alerts and recommendations generated by AI features.",
        icon: BrainCircuit,
    },

    {
        id: "systemMaintenanceNotifications",
        name: "System Maintenance Notifications",
        description:
            "Receive notifications about system maintenance and service availability.",
        icon: Wrench,
    },
];


// ============================================================
// STORAGE KEYS
// ============================================================

const NOTIFICATION_PREFERENCES_KEY =
    "notificationPreferences";

const ACTIVITY_LOGS_KEY =
    "activityLogs";


// ============================================================
// GET CURRENT USER
// ============================================================

function getCurrentUser() {
    try {
        const storedUser =
            localStorage.getItem("user");

        if (!storedUser) {
            return null;
        }

        const parsedUser =
            JSON.parse(storedUser);

        if (
            !parsedUser ||
            typeof parsedUser !== "object"
        ) {
            return null;
        }

        return parsedUser;

    } catch (error) {
        console.error(
            "Unable to read current user:",
            error
        );

        return null;
    }
}


// ============================================================
// GET USER IDENTIFIER
// ============================================================
//
// We support both:
// id
// userId
// email
//
// This keeps the component compatible with your existing
// authentication/localStorage structure.
// ============================================================

function getUserIdentifier(user) {
    if (!user) {
        return null;
    }

    if (
        user.id !== undefined &&
        user.id !== null
    ) {
        return String(user.id);
    }

    if (
        user.userId !== undefined &&
        user.userId !== null
    ) {
        return String(user.userId);
    }

    if (user.email) {
        return String(user.email)
            .trim()
            .toLowerCase();
    }

    return null;
}


// ============================================================
// DEFAULT PREFERENCES
// ============================================================

function createDefaultPreferences() {
    const preferences = {};

    DEFAULT_NOTIFICATION_TYPES.forEach(
        (notificationType) => {
            preferences[
                notificationType.id
            ] =
                notificationType.mandatory
                    ? true
                    : true;
        }
    );

    return preferences;
}


// ============================================================
// GET ALL NOTIFICATION PREFERENCES
// ============================================================

function getStoredNotificationPreferences() {
    try {
        const storedPreferences =
            localStorage.getItem(
                NOTIFICATION_PREFERENCES_KEY
            );

        if (!storedPreferences) {
            return {};
        }

        const parsedPreferences =
            JSON.parse(
                storedPreferences
            );

        if (
            !parsedPreferences ||
            typeof parsedPreferences !== "object"
        ) {
            return {};
        }

        return parsedPreferences;

    } catch (error) {
        console.error(
            "Unable to read notification preferences:",
            error
        );

        return {};
    }
}


// ============================================================
// GET CURRENT USER PREFERENCES
// ============================================================

function getUserNotificationPreferences(
    user
) {
    const userId =
        getUserIdentifier(user);

    if (!userId) {
        return null;
    }

    const allPreferences =
        getStoredNotificationPreferences();

    const savedPreferences =
        allPreferences[userId];

    const defaultPreferences =
        createDefaultPreferences();

    return {
        ...defaultPreferences,
        ...(savedPreferences || {}),
    };
}


// ============================================================
// SAVE USER NOTIFICATION PREFERENCES
// ============================================================

function saveUserNotificationPreferences(
    user,
    preferences
) {
    const userId =
        getUserIdentifier(user);

    if (!userId) {
        throw new Error(
            "User identifier not found."
        );
    }

    const allPreferences =
        getStoredNotificationPreferences();

    allPreferences[userId] =
        preferences;

    localStorage.setItem(
        NOTIFICATION_PREFERENCES_KEY,
        JSON.stringify(
            allPreferences
        )
    );
}


// ============================================================
// ACTIVITY / AUDIT LOG
// ============================================================

function addActivityLog(
    user,
    action,
    details = ""
) {
    try {
        const storedLogs =
            localStorage.getItem(
                ACTIVITY_LOGS_KEY
            );

        let logs = [];

        if (storedLogs) {
            try {
                const parsedLogs =
                    JSON.parse(
                        storedLogs
                    );

                if (
                    Array.isArray(
                        parsedLogs
                    )
                ) {
                    logs = parsedLogs;
                }
            } catch {
                logs = [];
            }
        }

        const newLog = {
            id: Date.now(),

            action,

            details,

            userId:
                user?.id ??
                user?.userId ??
                null,

            userName:
                user?.fullName ||
                user?.name ||
                "Unknown User",

            userEmail:
                user?.email ||
                "",

            timestamp:
                new Date().toISOString(),
        };

        logs.unshift(newLog);

        localStorage.setItem(
            ACTIVITY_LOGS_KEY,
            JSON.stringify(logs)
        );

    } catch (error) {
        console.error(
            "Unable to record activity log:",
            error
        );
    }
}


// ============================================================
// VALIDATE PREFERENCES
// ============================================================

function validateNotificationPreferences(
    preferences
) {
    if (
        !preferences ||
        typeof preferences !== "object"
    ) {
        return false;
    }

    for (
        const notificationType
        of DEFAULT_NOTIFICATION_TYPES
    ) {
        const value =
            preferences[
                notificationType.id
            ];

        // Every preference must be boolean.
        if (
            typeof value !==
            "boolean"
        ) {
            return false;
        }

        // Mandatory security alerts
        // must always remain enabled.
        if (
            notificationType.mandatory &&
            value !== true
        ) {
            return false;
        }
    }

    return true;
}


// ============================================================
// MAIN COMPONENT
// ============================================================

function NotificationPreferences() {

    // ========================================================
    // USER
    // ========================================================

    const [currentUser, setCurrentUser] =
        useState(null);


    // ========================================================
    // PREFERENCES
    // ========================================================

    const [preferences, setPreferences] =
        useState(
            createDefaultPreferences()
        );


    // ========================================================
    // ORIGINAL PREFERENCES
    //
    // Used for Cancel / Reset unsaved changes.
    // ========================================================

    const [originalPreferences, setOriginalPreferences] =
        useState(
            createDefaultPreferences()
        );


    // ========================================================
    // LOADING
    // ========================================================

    const [isLoading, setIsLoading] =
        useState(true);


    // ========================================================
    // SAVING
    // ========================================================

    const [isSaving, setIsSaving] =
        useState(false);


    // ========================================================
    // MESSAGE
    // ========================================================

    const [message, setMessage] =
        useState({
            type: "",
            text: "",
        });


    // ========================================================
    // DIRTY STATE
    // ========================================================

    const [hasChanges, setHasChanges] =
        useState(false);


    // ========================================================
    // LOAD CURRENT PREFERENCES
    // ========================================================

    useEffect(() => {

        const loadPreferences = () => {

            try {

                setIsLoading(true);

                const user =
                    getCurrentUser();

                // ==================================================
                // A4:
                // Admin account cannot be found.
                // ==================================================

                if (!user) {

                    setCurrentUser(null);

                    setMessage({
                        type: "error",
                        text:
                            "User preferences not found.",
                    });

                    return;
                }


                // ==================================================
                // AUTHORIZATION
                // ==================================================

                const role =
                    String(
                        user.role || ""
                    )
                        .trim()
                        .toLowerCase();

                if (
                    role &&
                    role !== "admin"
                ) {

                    setMessage({
                        type: "error",
                        text:
                            "Access denied. Only administrators can modify notification preferences.",
                    });

                    return;
                }


                // ==================================================
                // GET SAVED PREFERENCES
                // ==================================================

                const savedPreferences =
                    getUserNotificationPreferences(
                        user
                    );


                if (
                    !savedPreferences
                ) {

                    setMessage({
                        type: "error",
                        text:
                            "User preferences not found.",
                    });

                    return;
                }


                // ==================================================
                // STATE
                // ==================================================

                setCurrentUser(user);

                setPreferences(
                    savedPreferences
                );

                setOriginalPreferences(
                    savedPreferences
                );

                setHasChanges(false);

                setMessage({
                    type: "",
                    text: "",
                });

            } catch (error) {

                console.error(
                    "Unable to load notification preferences:",
                    error
                );

                setMessage({
                    type: "error",
                    text:
                        "Unable to load notification preferences. Please try again.",
                });

            } finally {

                setIsLoading(false);

            }
        };


        loadPreferences();

    }, []);


    // ========================================================
    // HANDLE TOGGLE
    // ========================================================

    const handleToggle = (
        preferenceId,
        checked
    ) => {

        // ==================================================
        // Find notification configuration.
        // ==================================================

        const notificationType =
            DEFAULT_NOTIFICATION_TYPES.find(
                (item) =>
                    item.id ===
                    preferenceId
            );


        // ==================================================
        // Mandatory security alerts
        // cannot be disabled.
        // ==================================================

        if (
            notificationType?.mandatory
        ) {

            setMessage({
                type: "error",
                text:
                    "Mandatory security alerts cannot be disabled.",
            });

            return;
        }


        // ==================================================
        // Update state only.
        //
        // Nothing is saved until Save Changes is clicked.
        // ==================================================

        setPreferences(
            (previous) => ({
                ...previous,

                [preferenceId]:
                    checked,
            })
        );

        setHasChanges(true);

        setMessage({
            type: "",
            text: "",
        });
    };


    // ========================================================
    // SAVE CHANGES
    // ========================================================

    const handleSave = () => {

        setMessage({
            type: "",
            text: "",
        });


        // ==================================================
        // A4:
        // User not found.
        // ==================================================

        if (!currentUser) {

            setMessage({
                type: "error",
                text:
                    "User preferences not found.",
            });

            return;
        }


        // ==================================================
        // BR6:
        // Validate before saving.
        // ==================================================

        const isValid =
            validateNotificationPreferences(
                preferences
            );


        if (!isValid) {

            setMessage({
                type: "error",
                text:
                    "One or more notification settings are invalid.",
            });

            return;
        }


        try {

            setIsSaving(true);


            // ==================================================
            // Save preferences.
            // ==================================================

            saveUserNotificationPreferences(
                currentUser,
                preferences
            );


            // ==================================================
            // Audit log.
            // ==================================================

            addActivityLog(
                currentUser,
                "Updated notification preferences",
                JSON.stringify(
                    preferences
                )
            );


            // ==================================================
            // Update original state.
            // ==================================================

            setOriginalPreferences(
                {
                    ...preferences,
                }
            );

            setHasChanges(false);


            // ==================================================
            // Success.
            // ==================================================

            setMessage({
                type: "success",
                text:
                    "Notification preferences updated successfully.",
            });

        } catch (error) {

            console.error(
                "Unable to save notification preferences:",
                error
            );

            // ==================================================
            // A2
            // ==================================================

            setMessage({
                type: "error",
                text:
                    "Unable to update notification preferences. Please try again.",
            });

        } finally {

            setIsSaving(false);

        }
    };


    // ========================================================
    // CANCEL CHANGES
    // ========================================================

    const handleCancel = () => {

        // ==================================================
        // BR8:
        // Cancel must not modify saved preferences.
        //
        // Restore the original values only in the UI.
        // ==================================================

        setPreferences(
            {
                ...originalPreferences,
            }
        );

        setHasChanges(false);

        setMessage({
            type: "",
            text: "",
        });
    };


    // ========================================================
    // RESET TO DEFAULTS
    // ========================================================

    const handleReset = () => {

        const defaultPreferences =
            createDefaultPreferences();

        setPreferences(
            defaultPreferences
        );

        setHasChanges(true);

        setMessage({
            type: "",
            text: "",
        });
    };


    // ========================================================
    // LOADING UI
    // ========================================================

    if (isLoading) {

        return (
            <div
                className="
                    flex
                    min-h-[400px]
                    items-center
                    justify-center
                    bg-background
                    text-foreground
                "
            >

                <div className="text-center">

                    <div
                        className="
                            mx-auto
                            mb-4
                            h-10
                            w-10
                            animate-spin
                            rounded-full
                            border-4
                            border-border
                            border-t-primary
                        "
                    />

                    <p
                        className="
                            text-sm
                            font-medium
                            text-muted-foreground
                        "
                    >
                        Loading notification preferences...
                    </p>

                </div>

            </div>
        );
    }


    // ========================================================
    // ACCESS / USER ERROR
    // ========================================================

    if (!currentUser) {

        return (
            <div
                className="
                    min-h-[400px]
                    bg-background
                    p-6
                    text-foreground
                "
            >

                <div
                    className="
                        mx-auto
                        max-w-3xl
                        rounded-xl
                        border
                        border-destructive/30
                        bg-destructive/10
                        p-6
                    "
                >

                    <div className="flex gap-3">

                        <AlertCircle
                            className="
                                h-5
                                w-5
                                shrink-0
                                text-destructive
                            "
                        />

                        <div>

                            <h2
                                className="
                                    font-semibold
                                    text-foreground
                                "
                            >
                                Unable to load preferences
                            </h2>

                            <p
                                className="
                                    mt-1
                                    text-sm
                                    text-muted-foreground
                                "
                            >
                                {message.text ||
                                    "User preferences not found."}
                            </p>

                        </div>

                    </div>

                </div>

            </div>
        );
    }


    // ========================================================
    // MAIN RENDER
    // ========================================================

    return (
        <div
            className="
                min-h-full
                bg-background
                p-4
                text-foreground
                md:p-6
            "
        >

            <div
                className="
                    mx-auto
                    max-w-5xl
                "
            >

                {/* ==================================================
                    HEADER
                ================================================== */}

                <div className="mb-6">

                    <div
                        className="
                            flex
                            items-start
                            gap-4
                        "
                    >

                        <div
                            className="
                                flex
                                h-12
                                w-12
                                shrink-0
                                items-center
                                justify-center
                                rounded-xl
                                bg-primary/10
                                text-primary
                            "
                        >

                            <Bell
                                className="
                                    h-6
                                    w-6
                                "
                            />

                        </div>


                        <div>

                            <h1
                                className="
                                    text-2xl
                                    font-bold
                                    tracking-tight
                                    text-foreground
                                    md:text-3xl
                                "
                            >
                                Notification Preferences
                            </h1>

                            <p
                                className="
                                    mt-1
                                    text-sm
                                    text-muted-foreground
                                "
                            >
                                Configure how and when you
                                receive AI-PMS notifications.
                            </p>

                        </div>

                    </div>

                </div>


                {/* ==================================================
                    MESSAGE
                ================================================== */}

                {message.text && (

                    <div
                        className={`
                            mb-6
                            flex
                            items-start
                            gap-3
                            rounded-xl
                            border
                            p-4

                            ${
                                message.type ===
                                "success"

                                    ? `
                                        border-emerald-500/30
                                        bg-emerald-500/10
                                        text-emerald-700
                                        dark:text-emerald-400
                                    `

                                    : `
                                        border-destructive/30
                                        bg-destructive/10
                                        text-destructive
                                    `
                            }
                        `}
                    >

                        {message.type ===
                        "success" ? (

                            <CheckCircle2
                                className="
                                    mt-0.5
                                    h-5
                                    w-5
                                    shrink-0
                                "
                            />

                        ) : (

                            <AlertCircle
                                className="
                                    mt-0.5
                                    h-5
                                    w-5
                                    shrink-0
                                "
                            />

                        )}

                        <p
                            className="
                                text-sm
                                font-medium
                            "
                        >
                            {message.text}
                        </p>

                    </div>

                )}


                {/* ==================================================
                    INFORMATION CARD
                ================================================== */}

                <div
                    className="
                        mb-6
                        rounded-xl
                        border
                        border-border
                        bg-card
                        p-5
                        shadow-sm
                    "
                >

                    <div
                        className="
                            flex
                            items-start
                            gap-3
                        "
                    >

                        <Bell
                            className="
                                mt-0.5
                                h-5
                                w-5
                                shrink-0
                                text-primary
                            "
                        />

                        <div>

                            <h2
                                className="
                                    font-semibold
                                    text-foreground
                                "
                            >
                                Manage your notifications
                            </h2>

                            <p
                                className="
                                    mt-1
                                    text-sm
                                    leading-6
                                    text-muted-foreground
                                "
                            >
                                Choose which types of
                                notifications you want to
                                receive. Changes will apply
                                to future notifications after
                                you save them.
                            </p>

                        </div>

                    </div>

                </div>


                {/* ==================================================
                    NOTIFICATION SETTINGS
                ================================================== */}

                <div
                    className="
                        overflow-hidden
                        rounded-2xl
                        border
                        border-border
                        bg-card
                        shadow-sm
                    "
                >

                    {/* CARD HEADER */}

                    <div
                        className="
                            border-b
                            border-border
                            p-5
                            md:p-6
                        "
                    >

                        <div
                            className="
                                flex
                                items-center
                                justify-between
                                gap-4
                            "
                        >

                            <div>

                                <h2
                                    className="
                                        text-lg
                                        font-bold
                                        text-foreground
                                    "
                                >
                                    Notification Types
                                </h2>

                                <p
                                    className="
                                        mt-1
                                        text-sm
                                        text-muted-foreground
                                    "
                                >
                                    Enable or disable the
                                    notification types available
                                    to your account.
                                </p>

                            </div>

                            <span
                                className="
                                    hidden
                                    rounded-full
                                    bg-primary/10
                                    px-3
                                    py-1
                                    text-xs
                                    font-semibold
                                    text-primary
                                    sm:inline-flex
                                "
                            >
                                {DEFAULT_NOTIFICATION_TYPES.length}{" "}
                                notification types
                            </span>

                        </div>

                    </div>


                    {/* SETTINGS LIST */}

                    <div
                        className="
                            divide-y
                            divide-border
                        "
                    >

                        {DEFAULT_NOTIFICATION_TYPES.map(
                            (notificationType) => {

                                const Icon =
                                    notificationType.icon;

                                const isEnabled =
                                    Boolean(
                                        preferences[
                                            notificationType.id
                                        ]
                                    );

                                return (

                                    <div
                                        key={
                                            notificationType.id
                                        }
                                        className="
                                            flex
                                            items-center
                                            justify-between
                                            gap-4
                                            p-5
                                            transition-colors
                                            hover:bg-muted/50
                                            md:p-6
                                        "
                                    >

                                        {/* LEFT */}

                                        <div
                                            className="
                                                flex
                                                min-w-0
                                                items-start
                                                gap-4
                                            "
                                        >

                                            <div
                                                className={`
                                                    flex
                                                    h-10
                                                    w-10
                                                    shrink-0
                                                    items-center
                                                    justify-center
                                                    rounded-lg

                                                    ${
                                                        isEnabled
                                                            ? `
                                                                bg-primary/10
                                                                text-primary
                                                            `
                                                            : `
                                                                bg-muted
                                                                text-muted-foreground
                                                            `
                                                    }
                                                `}
                                            >

                                                <Icon
                                                    className="
                                                        h-5
                                                        w-5
                                                    "
                                                />

                                            </div>


                                            <div
                                                className="
                                                    min-w-0
                                                "
                                            >

                                                <div
                                                    className="
                                                        flex
                                                        flex-wrap
                                                        items-center
                                                        gap-2
                                                    "
                                                >

                                                    <h3
                                                        className="
                                                            text-sm
                                                            font-semibold
                                                            text-foreground
                                                        "
                                                    >
                                                        {
                                                            notificationType.name
                                                        }
                                                    </h3>


                                                    {notificationType.mandatory && (

                                                        <span
                                                            className="
                                                                rounded-full
                                                                bg-amber-500/10
                                                                px-2
                                                                py-0.5
                                                                text-[10px]
                                                                font-semibold
                                                                text-amber-600
                                                                dark:text-amber-400
                                                            "
                                                        >
                                                            Required
                                                        </span>

                                                    )}

                                                </div>


                                                <p
                                                    className="
                                                        mt-1
                                                        max-w-2xl
                                                        text-sm
                                                        leading-5
                                                        text-muted-foreground
                                                    "
                                                >
                                                    {
                                                        notificationType.description
                                                    }
                                                </p>


                                                {notificationType.mandatory && (

                                                    <p
                                                        className="
                                                            mt-2
                                                            text-xs
                                                            font-medium
                                                            text-amber-600
                                                            dark:text-amber-400
                                                        "
                                                    >
                                                        Mandatory security
                                                        alerts cannot be
                                                        disabled.
                                                    </p>

                                                )}

                                            </div>

                                        </div>


                                        {/* SWITCH */}

                                        <div
                                            className="
                                                shrink-0
                                            "
                                        >

                                            <Switch
                                                checked={
                                                    isEnabled
                                                }
                                                onCheckedChange={(
                                                    checked
                                                ) =>
                                                    handleToggle(
                                                        notificationType.id,
                                                        checked
                                                    )
                                                }
                                                disabled={
                                                    notificationType.mandatory
                                                }
                                                aria-label={
                                                    `Toggle ${notificationType.name}`
                                                }
                                            />

                                        </div>

                                    </div>

                                );
                            }
                        )}

                    </div>


                    {/* ==================================================
                        ACTIONS
                    ================================================== */}

                    <div
                        className="
                            flex
                            flex-col-reverse
                            gap-3
                            border-t
                            border-border
                            bg-muted/30
                            p-5
                            sm:flex-row
                            sm:items-center
                            sm:justify-between
                            md:p-6
                        "
                    >

                        {/* RESET */}

                        <Button
                            type="button"
                            variant="ghost"
                            onClick={
                                handleReset
                            }
                            disabled={
                                isSaving
                            }
                            className="
                                gap-2
                                text-muted-foreground
                            "
                        >

                            <RotateCcw
                                className="
                                    h-4
                                    w-4
                                "
                            />

                            Reset to Defaults

                        </Button>


                        {/* RIGHT ACTIONS */}

                        <div
                            className="
                                flex
                                flex-col
                                gap-3
                                sm:flex-row
                            "
                        >

                            {/* CANCEL */}

                            <Button
                                type="button"
                                variant="outline"
                                onClick={
                                    handleCancel
                                }
                                disabled={
                                    isSaving ||
                                    !hasChanges
                                }
                                className="gap-2"
                            >

                                <X
                                    className="
                                        h-4
                                        w-4
                                    "
                                />

                                Cancel

                            </Button>


                            {/* SAVE */}

                            <Button
                                type="button"
                                onClick={
                                    handleSave
                                }
                                disabled={
                                    isSaving ||
                                    !hasChanges
                                }
                                className="gap-2"
                            >

                                {isSaving ? (

                                    <>

                                        <span
                                            className="
                                                h-4
                                                w-4
                                                animate-spin
                                                rounded-full
                                                border-2
                                                border-white/40
                                                border-t-white
                                            "
                                        />

                                        Saving...

                                    </>

                                ) : (

                                    <>

                                        <Save
                                            className="
                                                h-4
                                                w-4
                                            "
                                        />

                                        Save Changes

                                    </>

                                )}

                            </Button>

                        </div>

                    </div>

                </div>


                {/* ==================================================
                    SECURITY / BUSINESS RULE NOTE
                ================================================== */}

                <div
                    className="
                        mt-6
                        rounded-xl
                        border
                        border-blue-500/30
                        bg-blue-500/10
                        p-5
                    "
                >

                    <div
                        className="
                            flex
                            items-start
                            gap-3
                        "
                    >

                        <ShieldAlert
                            className="
                                mt-0.5
                                h-5
                                w-5
                                shrink-0
                                text-blue-600
                                dark:text-blue-400
                            "
                        />

                        <div>

                            <h3
                                className="
                                    text-sm
                                    font-bold
                                    text-foreground
                                "
                            >
                                Notification Security Rule
                            </h3>

                            <p
                                className="
                                    mt-1
                                    text-sm
                                    leading-6
                                    text-muted-foreground
                                "
                            >
                                Security alerts are mandatory
                                and cannot be disabled through
                                notification preferences.
                                This ensures that important
                                security events continue to
                                reach the administrator.
                            </p>

                        </div>

                    </div>

                </div>

            </div>

        </div>
    );
}

export default NotificationPreferences;